[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "inmydata>=0.0.16",
    "mcp>=1.15.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.1.1",
]
